version: '2'
services:
  web-pozos:
    image: httpd:2.4
    depends_on:
      - api
    ports:
      - "8082:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs/
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - api_pozos

  api:
    image: api-pozos:1
    ports:
      - "4000:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - api_pozos

networks:
  api_pozos:
